---
title: "ltevrnTEST"
author: "Laura Tomkins"
date: "April 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, echo = TRUE, include = TRUE)
devtools::load_all()
```

```{r add_test}
x = 1
y = 2
ztest <- ltevrn::add(x,y)

z = x+y

if (z==ztest){
  paste0("add test passed")
} else {
  paste0("add test failed")
}
```

```{r subtract_test}
vtest <- ltevrn::subtract(x,y)

v = x-y

if (v==vtest){
  paste0("subtract test passed")
} else {
  paste0("subtract test failed")
}
```

```{r hello_test}
greet <- "Hello, world!"
greettest <- ltevrn::hello()

if (greet==greettest){
  paste0("hello test passed")
} else {
  paste0("hello test failed")
}
```

```{r tempconvert_test}
temptest <- ltevrn::tempConvert(-40,"fahrenheit")

if (temptest==-40){
  paste0("tempConvert test passed")
} else {
  paste0("tempconvert test failed")
}
```

```{r treeheight_test}
height <- 60*tan(45*(pi/180))
heighttest <-  ltevrn::treeHeight(60,45,"degrees")

if (heighttest==height){
  paste0("treeHeight test passed")
} else {
  paste0("treeHeight test failed")
}
```

